# Generated by Django 4.2.9 on 2024-04-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessLocation',
            new_name='Student',
        ),
    ]
